# Generated by Django 4.2.3 on 2023-07-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Masters', 'Masters Degree')], max_length=25, null=True),
        ),
    ]
